Fix grammatical errors in UI messages
Cypherock/x1_wallet_firmware pull request #10
Opened 2022-09-09 14:59 UTC by ujjwal-cyph

2022-09-12 08:38 UTC, ujjwal-cyph commented on src/constant_texts.c
> +const char* ui_text_confirm_account = "Confirm Account: ";
```suggestion
const char* ui_text_confirm_account = "Confirm Account :";
```

2022-09-12 08:40 UTC, ujjwal-cyph commented on src/constant_texts.c
> +    "Invalid X1 Card Tap Card #4",
```suggestion
    "Invalid X1 Card\nTap Card #1",
    "Invalid X1 Card\nTap Card #2",
    "Invalid X1 Card\nTap Card #3",
    "Invalid X1 Card\nTap Card #4",
```

2022-09-12 10:42 UTC, ujjwal-cyph commented on src/constant_texts.c
> +const char* ui_text_card_detected = "Card detected, processing...";
```suggestion
const char* ui_text_card_detected = "Card detected Processing...";
```

2022-09-13 07:58 UTC, malviyagaurav requested changes

2022-09-13 12:36 UTC, malviyagaurav requested changes

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_send_transaction_with = "Send %s transaction with %s?";
```suggestion
const char* ui_text_send_transaction_with = "Send %s transaction with %s";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
>  const char* ui_text_eth_send_transaction_with = "Send %s transaction with %s on %s?";
```suggestion
const char* ui_text_eth_send_transaction_with = "Send %s transaction with %s on %s";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_near_add_account_with= "Add %s account with %s?";
```suggestion
const char* ui_text_near_add_account_with= "Add %s account with %s";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_recv_transaction_with = "Receive %s with %s?";
```suggestion
const char* ui_text_recv_transaction_with = "Receive %s with %s";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_eth_recv_transaction_with = "Receive %s with %s on %s?";
```suggestion
const char* ui_text_eth_recv_transaction_with = "Receive %s with %s on %s";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
>  const char* ui_text_output_send_value = "Receiver #%d\nSend %f\n%s?";
```suggestion
const char* ui_text_output_send_value = "Receiver #%d\nSend %f\n%s";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_start_firmware_update = "Update firmware to version %d.%d.%d?";
```suggestion
const char* ui_text_start_firmware_update = "Update firmware to version %d.%d.%d";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_sync_x1card_confirm = "Device will be synced with wallets in card, confirm?";
```suggestion
const char* ui_text_sync_x1card_confirm = "Device will be synced with wallets in card Confirm?";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_rotate_display_confirm = "Display will rotate 180 degrees, confirm?";
```suggestion
const char* ui_text_rotate_display_confirm = "Display will rotate 180 degrees\nConfirm?";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +    "You will need 2 X1 cards to perform factory reset",
```suggestion
    "You will need 2 cards to perform factory reset",
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +    "Make sure at least 2 X1 cards are accessible",
```suggestion
    "Make sure at least 2 cards are accessible",
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_confirm_factory_reset = "This will erase all accounts from device, confirm?";
```suggestion
const char* ui_text_confirm_factory_reset = "This will erase all wallets from device Confirm?";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_unauthenticate_via_cysync = "Authenticate the device via CySync";
```suggestion
const char* ui_text_unauthenticate_via_cysync = "Authenticate the device via the CySync app";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_its_a_while_check_your_cards = "It's been a while, kindly check if your cards are working properly";
```suggestion
const char* ui_text_its_a_while_check_your_cards = "It's been a while check if your cards are working properly";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_need_all_x1cards_to_delete_wallet_entirely = "You'll need all X1 Cards to delete this wallet entirely, confirm?";
```suggestion
const char* ui_text_need_all_x1cards_to_delete_wallet_entirely = "You'll need all cards to delete this wallet entirely, confirm?";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
>  const char* ui_text_sync_wallets_next_steps = "Sync Each wallet in next steps";
```suggestion
const char* ui_text_sync_wallets_next_steps = "Sync each wallet in next steps";
```

2022-09-13 12:36 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_pow_challenge_failed = "Wallet unlock failed, retry";
```suggestion
const char* ui_text_pow_challenge_failed = "Wallet unlock failed Retry";
```

2022-09-13 14:22 UTC, ujjwal-cyph commented on src/constant_texts.c
> +const char* ui_text_wallet_partial_fix = "Wallets in partial state, fix before proceeding";
Will overlap with button on the screen. not suggested.

2022-09-14 07:25 UTC, malviyagaurav approved these changes

2022-09-14 07:27 UTC, merged

2022-09-15 06:30 UTC, malviyagaurav commented on src/constant_texts.c
>  const char* ui_text_card_removed_fast = "Too fast, Tap again and wait for buzzer sound";
"Tap" to "tap"

2022-09-15 06:34 UTC, malviyagaurav commented on src/constant_texts.c
> +const char* ui_text_start_auth_from_CySync = "Authenticate device from the CySync App";
"App" to "app"

2022-09-15 06:34 UTC, malviyagaurav commented on src/constant_texts.c
>  const char* ui_text_check_cysync_app = "Check the CySync App";
"App" to "app"

2022-09-15 06:44 UTC, malviyagaurav commented on src/constant_texts.c
>          "Device provisioning ....."
"Device provisioning..."