Feat: Support wallet connect
Cypherock/x1_wallet_firmware pull request #107
Opened 2023-01-04 07:53 UTC by TejasvCypherock

2023-01-04 07:53 UTC, vbcypherock commented
Task linked: [CHI-2001 Wallet Connect Firmware Enabler](https://app.clickup.com/t/37308523/CHI-2001)

2023-01-04 12:55 UTC, ujjwal-cyph requested changes

2023-01-04 12:55 UTC, ujjwal-cyph commented on common/interfaces/user_interface/ui_input_text.c
> +                strncat(data->entered_text, &first_char_current_text, 1);
put this as a separate change request

2023-01-04 12:55 UTC, ujjwal-cyph commented on src/level_four/core/controller/send_transaction_controller_eth.c
> +    .gas_price      = {0},
this is a big PR. please undo unrelated changes.

2023-01-04 12:55 UTC, ujjwal-cyph commented on common/coin_support/near.c
> +  uint8_t digest[32] = {0};
please undo unrelated changes.

2023-01-04 12:55 UTC, ujjwal-cyph commented on common/interfaces/desktop_app_interface/communication.c
> +        return INVALID_PAYLOAD_LENGTH;
please undo unrelated changes.

2023-01-04 12:56 UTC, ujjwal-cyph commented on STM32L486RGTX_FLASH.ld
> +  FLASH    (rx)    : ORIGIN = 0x8023000,   LENGTH = 868K
not required

2023-01-05 05:28 UTC, ujjwal-cyph requested changes

2023-01-05 05:28 UTC, ujjwal-cyph commented on common/protocol_buffers/pb.h
> +/* Common parts of the nanopb library. Most of these are quite low-level
lets do the following: 
1. move the addition of protobuf as a separate independent PR with following things in mind
    a. first commit should link to the original commit files with a relevant reference of the specific commit
    b. second commit will incorporate all our relevant changes needed for our specific usage
3. move the entire protobuf from ~`common/protocol_buffers/`~ to `common/libraries/nanopb`

2023-01-05 05:28 UTC, ujjwal-cyph commented on common/coin_support/eth_sign_data/simple.pb.h
> +/* Automatically generated nanopb header */
please appropriately rename this file

suggestion(s):
1. `eip712.pb`

2023-01-05 05:28 UTC, ujjwal-cyph commented on .clang-format
> +IndentWidth: 4
better to take this change as a separate or at the least, a separate commit

2023-01-06 13:51 UTC, TejasvCypherock commented on src/level_four/core/controller/sign_message_controller_eth.c
> +            if (is_token_whitelisted(&var_send_transaction_data.transaction_metadata))
This case parallels SEND_TXN_UNSIGNED_TXN_RECEIVED_ETH in send flow.

2023-01-09 11:37 UTC, TejasvCypherock commented on common/coin_support/eth.c
> +        return false;
No, it won't. This else condition will only run when the payload size is greater than 0 and we do not support it.

2023-01-09 12:20 UTC, TejasvCypherock commented on common/coin_support/eth.c
> +bool get_data_as_string(const MessageData *msg_data, char *output, size_t out_length) {
obsolete function used for debugging, removed now.

2023-01-11 06:56 UTC, ujjwal-cyph commented on common/coin_support/eth.c
> +bool get_data_as_string(const MessageData *msg_data, char *output, size_t out_length) {
header still there. yet to remove

2023-01-12 12:30 UTC, kartikCypherock commented on common/coin_support/eth.c
> +static uint8_t ETH_DetectFunction(const uint32_t functionTag, Abi_Type_e const **dpAbiTypeArray) {
Suggestion taken

2023-01-12 12:30 UTC, kartikCypherock commented on common/coin_support/eth.c
> +            EvmFunctionSignature = (char *)EVM_swap_Signature;
Suggestion taken

2023-01-12 12:30 UTC, kartikCypherock commented on common/libraries/util/utils.c
> +        ((uint32_t)pCurrentSrcAddr < (uint32_t)pBaseAddr) || (readSize > totalSizeOfChunk)) {
Right, that makes sense. Suggestion taken

2023-01-12 13:32 UTC, TejasvCypherock commented on common/coin_support/eth.c
> +bool get_data_as_string(const MessageData *msg_data, char *output, size_t out_length) {
removed

2023-01-12 13:33 UTC, TejasvCypherock commented on common/coin_support/eth_sign_data/eip712_utils.h
> +queue_node *new_queue_node(TypedDataStruct_TypedDataNode *tree_node, const char *prefix) {
updated

2023-01-12 13:58 UTC, ujjwal-cyph commented on common/coin_support/eth.c
> +        return false;
```suggestion
```

2023-01-12 13:59 UTC, ujjwal-cyph commented on common/coin_support/eth.c
> +        return false;
changed

2023-01-30 11:49 UTC, TejasvCypherock commented on common/coin_support/eth_sign_data/simple.pb.c
> +/* Generated by nanopb-0.4.6 */
this will be picked up when we move the existing communication to protobuf

2023-01-30 16:38 UTC, ujjwal-cyph approved these changes

2023-01-30 16:39 UTC, merged