fix: add logs and increase memory for lvgl
Cypherock/x1_wallet_firmware pull request #152
Opened 2023-02-11 01:00 UTC by TejasvCypherock

2023-02-11 01:00 UTC, rohanagarwal94 commented
Task linked: [CHI-4521 BugFix: lvgl memory size increase](https://app.clickup.com/t/9002019994/CHI-4521)

2023-02-11 12:11 UTC, ujjwal-cyph requested changes

2023-02-11 12:11 UTC, ujjwal-cyph commented on common/startup/application_startup.c
> +    lv_log_register_print_cb((lv_log_print_g_cb_t)lv_custom_log_handler);
This explicit typecasting should not be needed.

2023-02-11 12:11 UTC, ujjwal-cyph commented on common/logger/logger.c
> +void lv_custom_log_handler(lv_log_level_t level, const char *file, int line, const char *dsc) {
the function prototype is wrong. Correction: 
```suggestion
void lv_custom_log_handler(lv_log_level_t level, const char *file, uint32_t line, const char *dsc) {
```

2023-02-11 12:31 UTC, ujjwal-cyph commented on common/lv_conf.h
> +#define LV_USE_LOG      1
this bumps the firmware binary size by `3256 bytes`. we might want to do this by different mechanism (directly modifying the `lv_mem_assert` macro in `lv_mem.h`.

2023-02-13 11:51 UTC, ujjwal-cyph approved these changes

2023-02-14 12:41 UTC, merged