Clear structures before decoding unsigned transactions
Cypherock/x1_wallet_firmware pull request #169
Opened 2023-02-25 12:17 UTC by TejasvCypherock

2023-02-25 12:17 UTC, rohanagarwal94 commented
Task linked: [CHI-4554 Bugfix: Clear structures before decoding unsigned transactions](https://app.clickup.com/t/9002019994/CHI-4554)

2023-02-27 04:11 UTC, amanCypherock requested changes
Should include this for APIs that populate data from byte array to other structures.

There are 3 such APIs in `coin_utils.c` and for `eth.c` the new API `eth_byte_array_to_msg`

2023-02-27 07:15 UTC, TejasvCypherock commented
> 

`eth_byte_array_to_msg` already has an explicit init funciton `eth_init_msg_data` which is being called before receiving the message in the flow.

2023-02-27 10:43 UTC, amanCypherock approved these changes

2023-02-27 10:47 UTC, merged