Fix derivation path checks
Cypherock/x1_wallet_firmware pull request #180
Opened 2023-03-09 13:22 UTC by ujjwal-cyph

2023-03-22 15:02 UTC, rohanagarwal94 commented
Task linked: [CHI-4582 Correct xpub/address derivation path checks on Device](https://app.clickup.com/t/9002019994/CHI-4582)

2023-04-26 07:20 UTC, TejasvCypherock requested changes

2023-04-26 07:20 UTC, TejasvCypherock commented on common/coin_support/coin_utils.h
> +#define IS_NON_HARDENED(x) ((x & 0x80000000) == 0)
We can convert this to inline functions to enforce type of x

2023-04-26 07:20 UTC, TejasvCypherock commented on common/coin_support/coin_utils.h
> +#define ADDR_DEFAULT_DEPTH 5
Add comments explaining why/how these are chosen or rename to make them clear

2023-04-26 07:20 UTC, TejasvCypherock commented on common/coin_support/solana.c
> +                IS_HARDENED(account) && change == 0x80000000);
Can we add 0x80000000 as a macro in solana.h

2023-04-26 11:29 UTC, TejasvCypherock approved these changes

2023-04-26 11:30 UTC, merged