refactor: Merge task and controller for create wallet flow
Cypherock/x1_wallet_firmware pull request #293
Opened 2023-06-12 09:36 UTC by kartikCypherock

2023-06-12 09:42 UTC, rohanagarwal94 commented
Task linked: [PRF-4796 Task controller merge - New wallet](https://app.clickup.com/t/9002019994/PRF-4796)

2023-06-12 11:51 UTC, ujjwal-cyph commented on src/menu/main_menu.c
> +extern void create_wallet(void);
add a todo or put at a relevant place

2023-06-13 06:06 UTC, amanCypherock requested changes
Please checkout the review comments here

2023-06-13 06:06 UTC, amanCypherock commented on src/level_three/add_wallet/controller/controller_new_wallet.c
> +      instruction_scr_destructor();
Remove `instruction_scr_destructor`, also on line 344

2023-06-13 08:44 UTC, kartikCypherock commented on src/level_three/add_wallet/controller/controller_new_wallet.c
> +      instruction_scr_destructor();
Fixed

2023-06-13 08:44 UTC, kartikCypherock commented on src/level_three/add_wallet/controller/controller_new_wallet.c
> +      input_text_init(
Ok, makes sense, I have split them in 2 states.

2023-06-13 08:44 UTC, kartikCypherock commented on src/level_three/add_wallet/controller/controller_new_wallet.c
> +#define EXIT 17
Yes, I have done it

2023-06-13 08:45 UTC, kartikCypherock commented on common/core/ui_state_machine.h
> +                              uint8_t state_on_p0_event);
Renamed as per suggestion, thanks

2023-06-13 08:45 UTC, kartikCypherock commented on src/menu/main_menu.c
> +extern void create_wallet(void);
Removed, will take this up seperately

2023-06-14 06:12 UTC, amanCypherock approved these changes

2023-06-14 06:19 UTC, merged