refactor: Correct size of struct members
Cypherock/x1_wallet_firmware pull request #348
Opened 2023-07-25 11:57 UTC by ujjwal-cyph

- [x] allow only supported input type
- [x] allow only supported output type
- [x] exactly one change output
- [x] change address validation
- [x] uppper limit on number of inputs & outputs
- [x] sign transaction inputs
- [x] send transaction script

2023-08-02 06:28 UTC, amanCypherock requested changes
Please update these minor changs

2023-08-02 06:28 UTC, amanCypherock commented on apps/btc_family/btc_txn.c
> +    return false;
Should clear hdnode as well?

2023-08-02 06:28 UTC, amanCypherock commented on apps/btc_family/btc_txn_helpers.c
> +                                    uint8_t *digest);
Please populate comments

2023-08-04 10:16 UTC, ujjwal-cyph commented on apps/btc_family/btc_helpers.c
> +  }
added a return code

2023-08-04 10:17 UTC, ujjwal-cyph commented on apps/btc_family/btc_txn_helpers.c
> +  if (!context->segwit_cache.filled) {
returning with a boolean now. this is now translated to the host as `unknown_error`. did not use ASSERT.

2023-08-04 10:17 UTC, ujjwal-cyph commented on apps/btc_family/btc_helpers.c
> +  }
moved this function `btc_script.c`

2023-08-04 10:18 UTC, ujjwal-cyph commented on apps/btc_family/btc_txn_helpers.c
> +                                    uint8_t *digest);
added

2023-08-04 10:18 UTC, ujjwal-cyph commented on apps/btc_family/btc_txn.c
> +    return false;
added

2023-08-04 12:21 UTC, kartikCypherock approved these changes

2023-08-05 05:40 UTC, amanCypherock approved these changes

2023-08-05 11:22 UTC, merged