Refactor/core framework evm
Cypherock/x1_wallet_firmware pull request #370
Opened 2023-08-12 05:32 UTC by natto1784

https://app.clickup.com/t/9002019994/PRF-4896
Requires https://github.com/Cypherock/cypherock-common/pull/29

2023-08-12 05:32 UTC, rohanagarwal94 commented
Task linked: [PRF-4896 Ethereum get public key function](https://app.clickup.com/t/9002019994/PRF-4896)

2023-08-17 08:55 UTC, natto1784 commented
rebased and made the changes

2023-08-17 08:56 UTC, natto1784 reviewed
already fixed in https://github.com/Cypherock/x1_wallet_firmware/pull/372
required for the CI build to pass

2023-08-18 06:27 UTC, natto1784 commented
rebased after https://github.com/Cypherock/x1_wallet_firmware/pull/373

2023-08-18 07:16 UTC, ujjwal-cyph requested changes

2023-08-18 07:16 UTC, ujjwal-cyph commented on apps/evm_family/evm_helpers.c
> +   * account model : m/44'/60'/x'/0/0
this comment is fine here but more importantly, the information can go into the doxygen comment as well.

2023-08-19 05:04 UTC, merged