feat: Implement 'NEAR' sign txn for transfer and add account fn call
Cypherock/x1_wallet_firmware pull request #379
Opened 2023-08-19 08:14 UTC by kartikCypherock

2023-08-19 08:25 UTC, rohanagarwal94 commented
Task linked: [PRF-4976 Near Send Transaction](https://app.clickup.com/t/9002019994/PRF-4976)

2023-08-24 07:35 UTC, kartikCypherock commented
Build issue is due to unmerged PR on the submodule: https://github.com/Cypherock/cypherock-common/pull/33

2023-08-28 14:09 UTC, ujjwal-cyph requested changes
please resolve conflicts

2023-08-28 14:09 UTC, ujjwal-cyph commented on apps/near_app/near_txn.c
> + * @param query Reference to an instance of btc_query_t containing query
`btc_query_t` left to rename

2023-08-29 05:33 UTC, kartikCypherock commented on apps/near_app/near_txn.c
> + * @param query Reference to an instance of btc_query_t containing query
updated

2023-08-29 06:03 UTC, ujjwal-cyph approved these changes

2023-08-29 09:41 UTC, amanCypherock approved these changes

2023-08-29 09:57 UTC, merged