chore: Remove dead code
Cypherock/x1_wallet_firmware pull request #412
Opened 2023-09-22 08:38 UTC by ujjwal-cyph

2023-12-15 10:27 UTC, amanCypherock reviewed
Do we need the function `byte_array_to_txn_metadata` ?

2023-12-15 10:28 UTC, amanCypherock requested changes
Do we need the function byte_array_to_txn_metadata ?

2023-12-15 10:47 UTC, ujjwal-cyph commented
> Do we need the function byte_array_to_txn_metadata ?

No. Removed it.

2023-12-16 04:56 UTC, amanCypherock approved these changes

2023-12-16 07:26 UTC, merged