Move format-string to source
Cypherock/x1_wallet_firmware pull request #42
Opened 2022-10-08 12:32 UTC by ujjwal-cyph

Fixes https://app.clickup.com/t/37308523/CHI-1934
The snprintf is getting string pointer instead of string literal which inhibits necessary compiler warnings

2022-10-10 06:33 UTC, vbcypherock commented
Task linked: [CHI-1934 Move const format strings to local file from constant_text.c](https://app.clickup.com/t/37308523/CHI-1934)

2022-11-03 10:02 UTC, amanCypherock commented
Can we solve this issue by using macro instead of string pointers for format strings?

2022-11-10 10:38 UTC, ujjwal-cyph commented
> Can we solve this issue by using macro instead of string pointers for format strings?

Changes ready

2022-11-22 08:41 UTC, amanCypherock requested changes

2022-11-22 08:41 UTC, amanCypherock commented on src/level_four/tap_cards/tasks/write_to_cards_tasks.c
> +        snprintf(display, sizeof(display), UI_TEX_TAP_CARD, ((flow_level.level_four-1)>>1)+1);
Mis-spelled TEXT

2022-11-22 08:44 UTC, amanCypherock approved these changes

2022-11-22 08:45 UTC, merged