fix(nfc): Error text updated for already tapped card
Cypherock/x1_wallet_firmware pull request #420
Opened 2023-10-10 10:08 UTC by amanCypherock

https://app.clickup.com/t/9002019994/PRF-6190

2023-10-10 10:08 UTC, rohanagarwal94 commented
Task linked: [PRF-6190 On device if same card is tapped in clear data flow then device says "wrong card sequence"](https://app.clickup.com/t/9002019994/PRF-6190)

2023-10-18 06:54 UTC, ujjwal-cyph commented on src/constant_texts.c
> +    "Tap another card\n Already tapped";
there was a comment to make this as "Tap another card". verify with @gauravmalviya-cypher

2023-10-18 06:57 UTC, ujjwal-cyph requested changes
finalize the message and update accordingly

2023-10-20 08:34 UTC, ujjwal-cyph approved these changes

2023-10-20 08:40 UTC, merged