fix(nfc): Report card error type on card errors during reconstruction
Cypherock/x1_wallet_firmware pull request #425
Opened 2023-10-18 14:27 UTC by amanCypherock

https://app.clickup.com/t/9002019994/PRF-6169

2023-10-18 14:28 UTC, rohanagarwal94 commented
Task linked: [PRF-6169 Device is sending "unknown X1 card error" on cysync when wallet is locked](https://app.clickup.com/t/9002019994/PRF-6169)

2023-10-18 14:28 UTC, rohanagarwal94 commented
Task linked: [PRF-6169 Device is sending "unknown X1 card error" on cysync when wallet is locked](https://app.clickup.com/t/9002019994/PRF-6169)

2023-10-18 14:28 UTC, rohanagarwal94 commented
Task linked: [PRF-6169 Device is sending "unknown X1 card error" on cysync when wallet is locked](https://app.clickup.com/t/9002019994/PRF-6169)

2023-10-20 12:24 UTC, ujjwal-cyph requested changes
change according to review comments.

2023-10-21 06:25 UTC, amanCypherock commented on src/wallet/reconstruct_wallet_flow.c
> +                  get_card_error_from_nfc_status(card_error_code));
Will update for CARD_OPERATION_P0_OCCURED.

Here CARD_OPERATION_ABORT_OPERATION is not P0 abort.
It indicates that the error is non-recoverable for the user. Refer enum comments

2023-10-21 08:30 UTC, amanCypherock commented on src/wallet/reconstruct_wallet_flow.c
> +                  get_card_error_from_nfc_status(card_error_code));
updated re-review

2023-10-23 09:12 UTC, ujjwal-cyph approved these changes

2023-10-23 12:23 UTC, merged