feat(core): Removed unnecessary steps for provisoning
Cypherock/x1_wallet_firmware pull request #442
Opened 2023-11-21 10:29 UTC by amanCypherock

Changes in this PR:
- USB enabled at startup in the initial app
- Joystick training and card training removed
- Handling of devices already provisioned improved to send a response to the host.
- Skipped confirmation for firmware update

2023-11-21 10:29 UTC, rohanagarwal94 commented
Task linked: [PRF-6523 Update the provisioning process to ship new firmware](https://app.clickup.com/t/9002019994/PRF-6523)

2023-11-23 12:35 UTC, ujjwal-cyph requested changes

2023-11-23 12:35 UTC, ujjwal-cyph commented on src/level_four/core/controller/initial_device_provision_contoller.c
> +          instruction_scr_destructor();
this doesn't seem to work as intended

2023-11-23 12:35 UTC, ujjwal-cyph commented on src/level_four/core/controller/initial_device_provision_contoller.c
> +          instruction_scr_destructor();
tried it on a physical device. the message did not appear

2023-12-01 11:40 UTC, merged