feat(core): Save wallet nonce while creation
Cypherock/x1_wallet_firmware pull request #443
Opened 2023-11-27 07:31 UTC by amanCypherock

With this change, the wallet ID is generated and verified every time the seed/mnemonics is reconstructed.
- This would prevent wallet collision when the two shares are generated from the same mnemonics and wallet name but in different sessions.

2023-11-27 07:31 UTC, rohanagarwal94 commented
Task linked: [PRF-6555 Verify wallet id on recreation](https://app.clickup.com/t/9002019994/PRF-6555)

2023-12-04 14:43 UTC, ujjwal-cyph commented on common/libraries/util/wallet_utilities.c
> +    log_hex_array("Generated wallet id: ", generated_wallet_id, WALLET_ID_SIZE);
is this intentional? this will bloat the logs.

2023-12-04 14:46 UTC, ujjwal-cyph requested changes
the functions `reconstruct_seed` & `reconstruct_mnemonics` have too much commonality. can we reduce the duplicity in logic? Since we are at this now.

2023-12-05 10:13 UTC, ujjwal-cyph commented on src/wallet/reconstruct_wallet_flow.c
> +uint8_t verify_wallet_and_generate_mnemonics(
static keyword missing

2023-12-05 10:14 UTC, ujjwal-cyph commented on src/wallet/reconstruct_wallet_flow.c
> +}
the call to `mnemonic_clear()` is missing in one of these functions.

2023-12-08 13:29 UTC, amanCypherock commented on src/wallet/reconstruct_wallet_flow.c
> +uint8_t verify_wallet_and_generate_mnemonics(
updated

2023-12-08 13:29 UTC, amanCypherock commented on src/wallet/reconstruct_wallet_flow.c
> +}
updated

2023-12-13 11:52 UTC, ujjwal-cyph commented on src/wallet/reconstruct_wallet_flow.c
> +  uint8_t secret[BLOCK_SIZE] = {0};
clean this buffer after its usage.

2023-12-13 11:54 UTC, ujjwal-cyph commented on common/libraries/util/wallet_utilities.c
> +    log_hex_array("Generated wallet id: ", generated_wallet_id, WALLET_ID_SIZE);
> This will happen in the older wallets 

i think you mean, invalid wallets (that don't pass this check).

2023-12-13 11:55 UTC, ujjwal-cyph approved these changes
LGTM. we can merge after closing the active comments.

2023-12-15 08:12 UTC, merged