feat(core): Record card write attempt
Cypherock/x1_wallet_firmware pull request #446
Opened 2023-12-06 13:29 UTC by amanCypherock

2023-12-06 13:29 UTC, rohanagarwal94 commented
Task linked: [PRF-6557 Verify wallet nonce on fetching a wallet](https://app.clickup.com/t/9002019994/PRF-6557)

2023-12-06 13:29 UTC, rohanagarwal94 commented
Task linked: [PRF-6558 Verify wallet before deleting](https://app.clickup.com/t/9002019994/PRF-6558)

2023-12-16 10:20 UTC, ujjwal-cyph commented on src/card_operations/card_write_share.c
> +  if (temp == (temp & wallet_for_flash->cards_states)) {
comment the reasoning here

2023-12-18 12:27 UTC, ujjwal-cyph requested changes
fix minor comments

2023-12-18 12:27 UTC, ujjwal-cyph commented on common/interfaces/flash_interface/flash_api.c
> +  return !(0x01 == (0x01 & (card_state >> (card_number - 1))));
add explanation in comments

2023-12-20 06:46 UTC, amanCypherock commented on src/card_operations/card_write_share.c
> +  if (temp == (temp & wallet_for_flash->cards_states)) {
added

2023-12-20 06:46 UTC, amanCypherock commented on common/interfaces/flash_interface/flash_api.c
> +  return !(0x01 == (0x01 & (card_state >> (card_number - 1))));
refactored

2023-12-20 09:53 UTC, merged