Prf 7071 remove dead code
Cypherock/x1_wallet_firmware pull request #478
Opened 2024-03-01 08:41 UTC by ParnikaGupta9

2024-03-01 08:41 UTC, rohanagarwal94 commented
Task linked: [PRF-7071 Remove the depreciated functionalities- Level four and three](https://app.clickup.com/t/9002019994/PRF-7071)

2024-03-02 13:31 UTC, ujjwal-cyph requested changes
rest looks okay.

2024-03-02 13:31 UTC, ujjwal-cyph commented on src/card_operations/card_unlock_wallet.c
> + * @file    card_read_verify_shares.c
match with the real file name.

2024-03-02 13:31 UTC, ujjwal-cyph commented on src/controller_main.c
>  Receive_Transaction_Data receive_transaction_data = {0};
remove these as well.

2024-03-02 13:31 UTC, ujjwal-cyph commented on src/card_operations/card_unlock_wallet.c
> -
undo this for maintaining the template

2024-03-02 13:31 UTC, ujjwal-cyph commented on src/card_operations/card_unlock_wallet.h
> +#include "nfc.h"
if possible move these into the source file.

2024-03-04 12:13 UTC, closed without merging