Improvement btc utxo parser
Cypherock/x1_wallet_firmware pull request #508
Opened 2024-05-18 05:38 UTC by vrockz747

PRF-7224: https://app.clickup.com/t/9002019994/PRF-7224
PRF-7200: https://app.clickup.com/t/9002019994/PRF-7200
PRF-7212: https://app.clickup.com/t/9002019994/PRF-7212

2024-05-29 08:27 UTC, ParnikaGupta9 requested changes

2024-05-29 08:30 UTC, vrockz747 commented on tests/apps/btc_app/btc_txn_helpers_tests.c
> +  }
Fixed it in commit 2af3ba3553120bb60c28c1f4d5e094e363a3c686

2024-05-29 08:33 UTC, vrockz747 commented on apps/btc_family/btc_txn.c
> +        0 != status) {
could you explain more, didn't get what you are referring to

2024-05-29 08:39 UTC, vrockz747 commented on apps/btc_family/btc_txn_helpers.c
> +    // TODO: UPDATE VAR-INT DECODE
current method assumes the `input-count` variable to be of single byte, which is of type `varint` and can varry upto 9 bytes as [specified.](https://en.bitcoin.it/wiki/Transaction).
This limitation of varint deocde is continued from the previous method and can be improved in future if required.

2024-05-29 08:42 UTC, vrockz747 commented on tests/apps/btc_app/btc_txn_helpers_tests.c
> +                                .value = 5000000000,    // Wrong value
yes the wrong value comment declares that the check is intended and expected to fail with return code of 3

2024-05-29 08:46 UTC, vrockz747 commented on tests/apps/btc_app/btc_txn_helpers_tests.c
>    // only fill necessary values
replaced a test case of legacy type to segwit type to test compatibility with segwit txns.
should add more comments to this, or add this entirely as a new test case?

2024-05-29 09:57 UTC, ParnikaGupta9 commented on tests/apps/btc_app/btc_txn_helpers_tests.c
>    // only fill necessary values
yes

2024-05-30 09:59 UTC, ParnikaGupta9 approved these changes

2024-05-30 10:00 UTC, merged