Replace strlen with strnlen
Cypherock/x1_wallet_firmware pull request #52
Opened 2022-10-26 09:04 UTC by amanCypherock

2022-10-26 09:04 UTC, vbcypherock commented
Task linked: [CHI-1972 Use strnlen instead of strlen](https://app.clickup.com/t/37308523/CHI-1972)

2022-10-29 07:24 UTC, ujjwal-cyph requested changes

2022-10-29 07:24 UTC, ujjwal-cyph commented on src/sdk_config.h
> +#define BSP_BUZZER_TIMER_COUNTER		9999
unrelated change

2022-10-29 07:24 UTC, ujjwal-cyph commented on src/sdk_config.h
> +#define BSP_BUZZER_TIMER_COUNTER		9999
```suggestion
#define BSP_BUZZER_TIMER_COUNTER		3799
```

2022-11-04 09:46 UTC, ujjwal-cyph approved these changes

2022-11-04 09:46 UTC, ujjwal-cyph commented on common/libraries/util/utils.c
> +        word_len = strnlen(input[i], 15);
```suggestion
        word_len = strnlen(input[i], 15);    // TODO: Define handling of overflow cases
```

2022-11-08 17:01 UTC, ujjwal-cyph approved these changes

2022-11-22 11:01 UTC, merged