added family id check before moving to pairing
Cypherock/x1_wallet_firmware pull request #54
Opened 2022-11-01 09:32 UTC by amanCypherock

https://app.clickup.com/t/37308523/CHI-2062

2022-11-01 09:32 UTC, vbcypherock commented
Task linked: [CHI-2062 Add family id check after card auth in main](https://app.clickup.com/t/37308523/CHI-2062)

2022-11-04 10:05 UTC, ujjwal-cyph commented
Add this change to `develop`

2022-11-04 10:30 UTC, ujjwal-cyph requested changes
Add this change to `develop`

2022-11-11 11:55 UTC, amanCypherock commented on src/level_four/core/controller/verify_card_controller.c
> +            uint32_t device_family_id = U32_READ_BE_ARRAY(get_family_id());
Not a problem with this PR or ticket.
paired_card_family seems better but remember it still has to be valid

2022-11-15 07:03 UTC, ujjwal-cyph approved these changes

2022-11-22 11:04 UTC, merged