Extend chain id size to support larger chain IDs
Cypherock/x1_wallet_firmware pull request #55
Opened 2022-11-07 11:08 UTC by ujjwal-cyph

Fixes https://app.clickup.com/t/37308523/CHI-2065

2022-11-07 11:08 UTC, vbcypherock commented
Task linked: [CHI-2065 Update metadata for larger Chain ID](https://app.clickup.com/t/37308523/CHI-2065)

2022-11-22 14:08 UTC, amanCypherock approved these changes

2022-11-22 14:11 UTC, amanCypherock requested changes
Need to update in CySync before merging

2022-11-23 09:18 UTC, amanCypherock approved these changes

2022-11-23 09:18 UTC, merged