feat(app): Add auth wallet tests
Cypherock/x1_wallet_firmware pull request #554
Opened 2024-09-17 11:23 UTC by vrockz747

2024-11-09 10:36 UTC, TejasvOnly requested changes

2024-11-09 10:36 UTC, TejasvOnly commented on .github/workflows/ci-tests.yml
Revert this change

2024-11-09 10:36 UTC, TejasvOnly commented on tests/unit_test_lists.c
> +}
Are these supposed to be in this pr?

2024-11-11 10:45 UTC, vrockz747 commented on tests/unit_test_lists.c
> +}
rebased correctly

2024-11-11 22:38 UTC, merged