Fix/inheritance/session refactor
Cypherock/x1_wallet_firmware pull request #560
Opened 2024-09-19 19:22 UTC by vrockz747

2024-09-20 09:55 UTC, TejasvOnly requested changes
Can we also take care of `USE_SIMULATOR` macros in this pr itself?

2024-09-20 09:55 UTC, TejasvOnly commented on common/core/core_session.c
> +  session.valid = true;
This should be done in `start_request` function

2024-09-20 09:55 UTC, TejasvOnly commented on common/core/core_session.c
> +  uint8_t hash[32] = {0};    // hash size reference taken from the atecc_sign
```suggestion
  uint8_t hash[SHA256_DIGEST_LENGTH] = {0};
```

2024-09-20 09:55 UTC, TejasvOnly commented on common/core/core_session.c
> +  uint8_t hash[32] = {0};
```suggestion
  uint8_t hash[SHA256_DIGEST_LENGTH] = {0};
```

2024-09-20 09:55 UTC, TejasvOnly commented on common/core/core_session.c
> +  session_ctx = (session_ctx_t *)cy_malloc(sizeof(session_ctx_t));
I don't think we need `cy_malloc`, we can simple use `malloc` as the `session_ctx` should only be in scope for this function and there are no early exits.

2024-09-20 09:57 UTC, TejasvOnly commented on common/core/core_session.c
> +  session.valid = true;
Not here, but we can simple use `malloc` and `free` in the `core_session_parse_start_message` function.

2024-09-20 10:01 UTC, vrockz747 commented
> Can we also take care of `USE_SIMULATOR` macros in this pr itself?

I was thinking of fixing it in the error handling PR, but will do in this only

2024-09-20 17:16 UTC, vrockz747 commented
> Can we also take care of `USE_SIMULATOR` macros in this pr itself?

I was thinking of fixing it in the error handling PR, but will do in this only

2024-09-23 13:04 UTC, TejasvOnly requested changes

2024-09-23 13:04 UTC, TejasvOnly commented on common/core/core_session.c
> +  // TODO: standardize simulator handling for hardware specific functionality
Should've been moved with the `#if`

2024-10-07 07:19 UTC, vrockz747 commented on common/core/core_session.h
> +  SESSION_ONGOING
had already updated them in #563

2024-11-14 09:45 UTC, merged