[WIP] Refactor signing of receive address
Cypherock/x1_wallet_firmware pull request #67
Opened 2022-11-20 11:53 UTC by arnabCypherock

2022-11-20 11:53 UTC, vbcypherock commented
Task linked: [CHI-2055 Changelly Hardware Enabler](https://app.clickup.com/t/37308523/CHI-2055)

2022-11-20 16:48 UTC, ujjwal-cyph requested changes

2022-11-20 17:04 UTC, ujjwal-cyph commented on common/libraries/util/utils.h
> +#include "controller_level_four.h" // for attecc_slot_define_t
do not import this header. instead move the definition here.

2022-11-21 08:55 UTC, ujjwal-cyph requested changes

2022-11-21 08:55 UTC, ujjwal-cyph commented on src/level_four/core/controller/receive_transaction_controller.c
> +#define AUTH_DATA_CHALLENGE_SIGN_MSG_SIZE   (POSTFIX1_SIZE + POSTFIX2_SIZE + SIGNATURE_SIZE)
move this to utils

2022-11-21 08:55 UTC, ujjwal-cyph commented on src/level_four/core/controller/receive_transaction_controller.c
> +            uint8_t payload[43 + SESSION_ID_SIZE];
keep the signing inside a function in utils

2022-11-21 08:55 UTC, ujjwal-cyph commented on src/level_four/core/controller/receive_transaction_controller.c
> +            uint8_t hash[32];
```suggestion
            uint8_t hash[32] = {0};
```

2022-11-21 08:55 UTC, ujjwal-cyph commented on common/coin_support/coin_utils.c
> +        memcpy(signed_recv_addr_byte_array, signed_recv_addr_ptr->session_id, sizeof(signed_recv_addr_ptr->session_id));
put an overflow check on `signed_recv_addr_byte_array`

2022-11-21 08:55 UTC, ujjwal-cyph commented on common/libraries/util/utils.c
> +void helper_get_gendig_hash(atecc_slot_define_t slot, uint8_t *data, uint8_t *digest, uint8_t *postfix)
keep all additions in a new file `atecc_utils`

2022-11-23 11:49 UTC, ujjwal-cyph commented
replaced by https://github.com/Cypherock/x1_wallet_firmware/pull/69

2022-11-23 11:49 UTC, closed without merging